# Generated by Django 4.2.7 on 2023-11-05 22:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_user_bio"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="default.png", upload_to="avatars"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="basic info"
            ),
        ),
    ]
