# Generated by Django 4.2.7 on 2023-11-06 18:53

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_slug_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=128, unique=True, validators=[blog.utils.validate_title]
            ),
        ),
    ]
