# Generated by Django 4.2.7 on 2023-11-07 22:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                related_name="post_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
