# Generated by Django 4.2.7 on 2024-01-12 23:55

from django.db import migrations
import martor.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_alter_post_likes_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=martor.models.MartorField(),
        ),
    ]
