# Generated by Django 4.2.7 on 2023-11-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="avatars"),
        ),
    ]
