# Generated by Django 4.2.7 on 2023-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="default.png", upload_to="avatars"),
        ),
    ]
