# Generated by Django 4.2.7 on 2023-11-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(
                max_length=255, null=True, verbose_name="basic info"
            ),
        ),
    ]
